name: Release
on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn install
      - run: yarn make
      - run: yarn release
